name: RPGItemsReloaded
main: net.rllcommunity.plugins.rpgitems.RpgItems
version: maven-version
#dev-url: http://dev.bukkit.org/server-mods/rpg-items/
softdepend: [WorldGuard]
commands:
    rpgitem:
        description: RPG Items
        usage: 